# Generated by Django 5.0.4 on 2024-04-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='default_username', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='UID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='SocialMediaTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('refresh_token', models.CharField(max_length=255)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
